# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('productora', models.CharField(max_length=10)),
                ('fecha', models.IntegerField()),
                ('temporada', models.IntegerField()),
                ('genero', models.IntegerField(choices=[(0, 'Accion'), (1, 'Historica'), (2, 'Terror'), (3, 'Drama'), (4, 'Ficcion'), (5, 'Policiaca')])),
                ('estado', models.IntegerField(choices=[(0, 'Produccion'), (1, 'En Emision'), (2, 'Finalizada')])),
            ],
        ),
    ]
